name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-workers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'
        
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: push Docker build
        run: |
          docker buildx build --push --platform linux/amd64,linux/arm64 \
          -t ${{ secrets.DOCKER_USERNAME }}/better-up-turbo:linux .

  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production server via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            
            echo "FromEmail=${{ secrets.FROM_EMAIL }}
            SmptHost=${{ secrets.SMTP_HOST }}
            SmptPort=${{ secrets.SMTP_PORT }}
            SmptIP=${{ secrets.SMTP_IP }}
            REGION=India
            DB-PASSWORD=9059015626
            AppPassword=${{ secrets.APP_PASSWORD }}" > .env

            sudo docker network create better-up || true

            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/better-up-publisher:linux
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/better-up-consumer:linux
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/better-up-nfserver:linux
            
            sudo docker network create better-up || true

            sudo docker rm -f better-up-publisher || true
            sudo docker rm -f better-up-consumer || true
            sudo docker rm -f better-up-nfserver || true

            sudo docker run -d \
              --name better-up-publisher \
              --network better-up \
              -v /home/ubuntu/.env:/app/publisher/.env \
              better-up-publisher:linux
            

            sudo docker run -d \
              --name better-up-consumer \
              --network better-up \
              -v /home/ubuntu/.env:/app/consumer/.env \
              better-up-consumer:linux

            sudo docker run -d \
              --name better-up-nfserver \
              --network better-up \
              -v /home/ubuntu/.env:/app/nf-server/.env \
              better-up-nfserver:linux


      



      



  
